"""empty message

Revision ID: a7fc996c33d5
Revises: 1eafa7b98e3a
Create Date: 2025-08-08 16:43:51.854541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7fc996c33d5'
down_revision = '1eafa7b98e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=postgresql.ENUM('IMAGE', 'VIDEO', 'AUDIO', name='type'),
               type_=sa.String(length=5),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username')
        batch_op.drop_constraint('user_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.create_index('ix_user_username', ['username'], unique=True)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(length=5),
               type_=postgresql.ENUM('IMAGE', 'VIDEO', 'AUDIO', name='type'),
               existing_nullable=False)

    # ### end Alembic commands ###
