"""empty message

Revision ID: e3fa7b43651b
Revises: a7fc996c33d5
Create Date: 2025-08-08 16:47:53.261158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3fa7b43651b'
down_revision = 'a7fc996c33d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_from_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('follower_user_origin_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_from_id'], ['id'])
        batch_op.drop_column('user_origin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_origin_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('follower_user_origin_id_fkey', 'user', ['user_origin_id'], ['id'])
        batch_op.drop_column('user_from_id')

    # ### end Alembic commands ###
